language: android

sudo: false

android:
    components:
        # Use the latest SDK build tools
        - platform-tools
        - tools

        # The BuildTools version used by your project
        - build-tools-23.0.3

        # The SDK version used to compile your project
        - android-23

        # Additional components
        - extra-google-google_play_services
        - extra-google-m2repository
        - extra-android-m2repository
jdk:
  - oraclejdk7
script:
  - ./gradlew external-resources:testDebugUnitTest -i
